const {chromium}=require('playwright-core');const assert=require('node:assert/strict');
const base=process.env.BASE_URL||'http://127.0.0.1:8921';
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM});try{const p=await b.newPage({viewport:{width:390,height:844}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/login.php',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.setItem('tema','niras'));await p.reload({waitUntil:'networkidle'});assert.equal(await p.locator('html').getAttribute('data-tema'),'jardim');assert.equal(await p.evaluate(()=>localStorage.getItem('tema')),'jardim');assert.equal(await p.title(),'Entrar · Kulemba');assert(!(await p.locator('body').innerText()).includes('Gestão de Convidados'));
const colors=await p.evaluate(()=>{const s=getComputedStyle(document.documentElement);return [s.getPropertyValue('--forest').trim(),s.getPropertyValue('--gold-soft').trim(),s.getPropertyValue('--ivory').trim()]});assert.deepEqual(colors,['#16283A','#63B22B','#F6F8F4']);
for(const tema of ['jardim','classico','azul','escuro']){await p.goto(base+'/login.php',{waitUntil:'networkidle'});await p.evaluate(t=>temaEscolher(t),tema);for(const url of ['login.php','registo.php','atendimento.php']){await p.goto(base+'/'+url,{waitUntil:'networkidle'});const im=p.locator('.marca-oficial');assert.equal(await im.count(),url==='registo.php'?2:1);const ok=await im.evaluateAll(xs=>xs.every(e=>{const r=e.getBoundingClientRect();return e.complete&&e.naturalWidth>0&&Math.abs(r.width/r.height-e.naturalWidth/e.naturalHeight)<.02}));assert(ok,'logo proportion '+tema+' '+url);assert(await im.evaluateAll(xs=>xs.every(e=>e.getAttribute('alt')==='Kulemba')));assert(!(await p.locator('body').innerText()).includes('NIRAS'));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),url+' overflow');if(tema==='escuro'||url==='atendimento.php')assert(await im.evaluateAll(xs=>xs.every(e=>getComputedStyle(e).filter.includes('invert(1)'))));if(process.env.SCREENSHOTS&&url==='login.php')await p.screenshot({path:process.env.SCREENSHOTS+'/kulemba-'+tema+'.png'});}}
await p.goto(base+'/login.php');await p.fill('[name=utilizador]','admin@local');await p.fill('[name=senha]','noivos2026');await p.click('button[type=submit]');await p.waitForLoadState('networkidle');await p.goto(base+'/plataforma.php',{waitUntil:'networkidle'});assert((await p.locator('body').textContent()).includes('Jardim Nocturno'));const data=await p.evaluate(async()=>await(await fetch('api.php?action=sistema_tema_guardar',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':window.CSRF},body:JSON.stringify({tema:'jardim'})})).json());assert(data.success&&data.rotulo==='Jardim Nocturno');
const m=await p.request.get(base+'/manifest.php');const manifest=await m.json();assert(manifest.name.startsWith('Kulemba'));assert.equal(manifest.short_name,'Kulemba');for(const icon of manifest.icons){assert((await p.request.get(base+'/'+icon.src)).ok())}
assert.deepEqual(errors,[]);console.log('PASS Kulemba: branding on three public pages in four themes, proportional logo, mobile layout, legacy browser preference, unchanged palette, admin save and PWA');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
