<?php
require_once __DIR__ . '/db.php';
function atDef(mysqli $c): array { global $P; $o=[]; $r=$c->query("SELECT chave,valor FROM {$P}definicoes WHERE casamento_id=0 AND chave LIKE 'atendimento.%'"); if($r) while($x=$r->fetch_row())$o[substr($x[0],12)]=$x[1]; return $o; }
function atConteudo(mysqli $c,string $tipo): array { global $P; $st=$c->prepare("SELECT modulo,titulo,resumo,conteudo,dados FROM {$P}atendimento_conteudos WHERE tipo=? AND ativo=1 ORDER BY ordem,id"); $st->bind_param('s',$tipo); $st->execute(); return $st->get_result()->fetch_all(MYSQLI_ASSOC); }
$d=atDef($conn); $demos=atConteudo($conn,'demo');
$faq=[]; $r=$conn->query("SELECT pergunta,resposta FROM {$P}atendimento_faq WHERE ativo=1 ORDER BY ordem,id"); if($r)$faq=$r->fetch_all(MYSQLI_ASSOC);
$rot=['convidados'=>'Convidados','mesas'=>'Mesas','impresso'=>'Convite impresso','digital'=>'Convite digital','porta'=>'Porta','bar'=>'Bar','orcamento'=>'Orçamento'];
function atDados(string $txt): array { $out=[]; foreach(preg_split('/\R/',$txt) as $l){$p=explode(':',$l,2);if(count($p)===2&&trim($p[0])!=='')$out[]=[trim($p[0]),trim($p[1])];} return array_slice($out,0,4); }
?><!doctype html><html lang="pt"><head><?php include __DIR__.'/parcial-icone.php'; ?>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">
<title>Conheça a plataforma · <?= escP(PLATAFORMA['nome']) ?></title>
<link rel="stylesheet" href="<?= asset('assets/fontes.css') ?>"><link rel="stylesheet" href="<?= asset('assets/estilo.css') ?>"><link rel="stylesheet" href="<?= asset('assets/central.css') ?>"><?php include __DIR__.'/parcial-tema.php'; ?></head>
<body class="central-publica"><header class="mk-topo"><a class="mk-marca" href="login.php"><img src="<?= asset('assets/'.PLATAFORMA['marca']) ?>" alt=""><span><?= escP(PLATAFORMA['nome']) ?></span></a><nav><a href="#demonstracao">Ver demonstração</a><a href="#perguntas">Perguntas</a><a class="mk-entrar" href="login.php">Entrar</a></nav></header>
<main>
<section class="mk-hero"><div><span class="mk-selo">Gestão completa do casamento</span><h1><?= escP($d['titulo']??'O vosso casamento, organizado com serenidade') ?></h1><p><?= escP($d['promessa']??'') ?></p><ul><?php foreach(array_filter(array_map('trim',preg_split('/\R/',$d['destaques']??''))) as $x): ?><li><?= escP($x) ?></li><?php endforeach ?></ul><div class="mk-acoes"><a class="btn btn-ouro" href="#demonstracao"><?= escP($d['cta_rotulo']??'Ver a plataforma') ?></a><a class="btn" href="registo.php">Criar conta</a></div></div>
<aside class="mk-consultora"><?php if(!empty($d['foto'])):?><img src="<?= escP($d['foto']) ?>" alt="<?= escP($d['nome']??'Atendimento') ?>"><?php endif ?><div><b><?= escP($d['nome']??'Atendimento') ?></b><span><?= escP($d['cargo']??'') ?></span><p><?= escP($d['saudacao']??'') ?></p></div></aside></section>
<section id="demonstracao" class="mk-seccao"><div class="mk-intro"><span class="mk-selo">Experimente antes de escolher</span><h2>Uma visão geral de cada módulo</h2><p>Todos os nomes, valores e movimentos abaixo são fictícios. A demonstração é isolada e não dá acesso aos dados nem às ferramentas internas da plataforma.</p></div>
<div class="demo-abas" role="tablist"><?php foreach($demos as $i=>$x): ?><button role="tab" aria-selected="<?= $i?'false':'true' ?>" data-demo="<?= escP($x['modulo']) ?>"><?= escP($rot[$x['modulo']]??$x['titulo']) ?></button><?php endforeach ?></div>
<?php foreach($demos as $i=>$x): $m=$x['modulo']; ?><article class="demo-painel" data-painel="<?= escP($m) ?>" <?= $i?'hidden':'' ?>><div class="demo-copia"><span><?= escP($rot[$m]??$m) ?></span><h3><?= escP($x['titulo']) ?></h3><p><?= nl2br(escP($x['conteudo'])) ?></p><a href="registo.php">Quero este módulo <b>→</b></a></div><div class="demo-janela" aria-label="Pré-visualização com dados fictícios"><div class="demo-barra"><i></i><i></i><i></i><strong><?= escP($rot[$m]??$m) ?></strong></div><div class="demo-watermark" aria-hidden="true">DEMONSTRAÇÃO · DADOS FICTÍCIOS</div><div class="demo-metricas"><?php foreach(atDados($x['dados']??'') as [$a,$b]): ?><div><span><?= escP($a) ?></span><b><?= escP($b) ?></b></div><?php endforeach ?></div><div class="demo-linhas"><?php for($j=0;$j<4;$j++): ?><div><i></i><span></span><em></em></div><?php endfor ?></div></div></article><?php endforeach ?></section>
<section id="perguntas" class="mk-seccao mk-faq"><div class="mk-intro"><span class="mk-selo">Decida com confiança</span><h2>Perguntas frequentes</h2></div><div><?php foreach($faq as $i=>$x): ?><details <?= $i===0?'open':'' ?>><summary><?= escP($x['pergunta']) ?></summary><p><?= nl2br(escP($x['resposta'])) ?></p></details><?php endforeach ?></div></section>
<section class="mk-final"><h2>Menos folhas soltas. Mais tempo para viver o casamento.</h2><p>Escolham apenas os módulos de que precisam e acompanhem tudo numa experiência pensada para telemóvel e computador.</p><a class="btn btn-ouro" href="registo.php">Começar agora</a></section>
</main><footer>© <?= date('Y') ?> <?= escP(PLATAFORMA['nome']) ?> · <a href="login.php">Entrar</a></footer><script src="<?= asset('assets/central.js') ?>"></script></body></html>
