<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/parcial-marca.php';
require_once __DIR__ . '/parcial-ajuda.php';
function atDef(mysqli $c): array { global $P; $o=[]; $r=$c->query("SELECT chave,valor FROM {$P}definicoes WHERE casamento_id=0 AND chave LIKE 'atendimento.%'"); if($r) while($x=$r->fetch_row())$o[substr($x[0],12)]=$x[1]; return $o; }
function atConteudo(mysqli $c,string $tipo): array { global $P; $st=$c->prepare("SELECT modulo,titulo,resumo,conteudo,dados FROM {$P}atendimento_conteudos WHERE tipo=? AND ativo=1 ORDER BY ordem,id"); $st->bind_param('s',$tipo); $st->execute(); return $st->get_result()->fetch_all(MYSQLI_ASSOC); }
$d=atDef($conn); $itens=atConteudo($conn,'demo');
$faq=[]; $r=$conn->query("SELECT pergunta,resposta FROM {$P}atendimento_faq WHERE ativo=1 ORDER BY ordem,id"); if($r)$faq=$r->fetch_all(MYSQLI_ASSOC);
$rot=['convidados'=>'Convidados','mesas'=>'Mesas','impresso'=>'Convite impresso','digital'=>'Convite digital','porta'=>'Porta','bar'=>'Bar','orcamento'=>'Orçamento'];
$ico=['convidados'=>'pessoas','mesas'=>'mesa','impresso'=>'carta','digital'=>'telemovel','porta'=>'porta','bar'=>'taca','orcamento'=>'moeda'];
$itens=array_values(array_filter($itens,fn($x)=>isset($rot[$x['modulo']])));
?><!doctype html><html lang="pt"><head><?php include __DIR__.'/parcial-icone.php'; ?>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="Experimente os convites, mesas, entradas, bebidas e orçamento do seu casamento numa demonstração interactiva.">
<title>Conheça a plataforma · <?= escP(PLATAFORMA['nome']) ?></title>
<link rel="stylesheet" href="<?= asset('assets/fontes.css') ?>"><link rel="stylesheet" href="<?= asset('assets/estilo.css') ?>"><link rel="stylesheet" href="<?= asset('assets/central.css') ?>"><link rel="stylesheet" href="<?= asset('assets/ajuda.css') ?>"><?php include __DIR__.'/parcial-tema.php'; ?></head>
<body class="central-publica"><header class="mk-topo"><a class="mk-marca" href="login.php" aria-label="Kulemba — entrar"><?php marcaKulemba('sobre-escuro'); ?></a><nav aria-label="Menu"><a href="#demonstracao">Experimentar</a><a href="#perguntas">Perguntas</a><a class="mk-entrar" href="login.php">Entrar</a></nav></header>
<main>
<section class="mk-hero"><div class="mk-hero-texto"><span class="mk-selo">Do primeiro convite ao último brinde</span><h1><?= escP($d['titulo']??'O vosso casamento, organizado com serenidade') ?></h1><p><?= escP($d['promessa']??'') ?></p><ul><?php foreach(array_filter(array_map('trim',preg_split('/\R/',$d['destaques']??''))) as $x): ?><li><?= escP($x) ?></li><?php endforeach ?></ul><div class="mk-acoes"><a class="btn btn-ouro" href="#demonstracao"><?= escP($d['cta_rotulo']??'Experimentar a plataforma') ?> <span aria-hidden="true">↗</span></a><a class="btn mk-secundario" href="registo.php">Criar conta</a></div><span class="mk-nota">Explore sem registo · Funciona no telemóvel</span></div>
<div class="mk-retrato"><img src="assets/convite/galeria/capa-jardim-solar.jpg" alt="Casal fictício a celebrar num jardim" fetchpriority="high"><div class="mk-flutuante"><span data-ico="anel"></span><div><b>Lia &amp; Daniel</b><span>Um dia especial. Tudo no seu lugar.</span></div></div><span class="mk-foto-nota">Uma história de exemplo, para imaginar a vossa.</span></div></section>
<section class="mk-percurso" aria-label="Da organização à celebração"><div><span data-ico="carta"></span><b>Convide com personalidade</b><p>Do papel ao telemóvel, o mesmo cuidado.</p></div><div><span data-ico="mesa"></span><b>Organize com clareza</b><p>Cada pessoa, cada lugar, cada despesa.</p></div><div><span data-ico="taca"></span><b>Viva o grande dia</b><p>Entradas e serviço a trabalhar em conjunto.</p></div></section>
<section class="mk-cinema" aria-label="A plataforma acompanha toda a celebração"><img src="<?= asset('assets/marketing/demonstracao-kulemba.webp') ?>" alt="Recepção de casamento organizada ao pôr do sol" loading="lazy"><div class="mk-cinema-copia"><span class="mk-selo">Tudo ligado, no momento certo</span><h2>Da primeira lista à última entrega.</h2><p>Os noivos decidem. A porta, a copa e a equipa executam. A Kulemba mantém todos alinhados.</p></div><div class="mk-cinema-cartoes" aria-hidden="true"><span><i data-ico="porta"></i><b>Entrada</b><small>87 presentes</small></span><span><i data-ico="taca"></i><b>Serviço</b><small>3 entregas</small></span><span><i data-ico="moeda"></i><b>Orçamento</b><small>sob controlo</small></span></div></section>
<section id="demonstracao" class="mk-seccao mk-ajuda-publica"><div class="aj-wrap"><?php renderCentralAjuda($itens,$rot,$ico,'demonstracao'); ?></div></section>
<section class="mk-acompanhamento"><div><span class="mk-selo">Do vosso lado, em cada passo</span><h2>Uma plataforma. Um apoio próximo.</h2><p>Escolham os módulos de que precisam e descubram, um a um, o que cada recurso vos poupa e oferece.</p><a class="btn btn-ouro" href="registo.php">Preparar o nosso casamento</a></div><aside class="mk-consultora"><?php if(!empty($d['foto'])):?><img loading="lazy" src="<?= escP($d['foto']) ?>" alt="<?= escP($d['nome']??'Atendimento') ?>"><?php endif ?><div><b><?= escP($d['nome']??'Atendimento') ?></b><span><?= escP($d['cargo']??'') ?></span><p><?= escP($d['saudacao']??'') ?></p></div></aside></section>
<section id="perguntas" class="mk-seccao mk-faq"><div class="mk-intro"><span class="mk-selo">Decida com confiança</span><h2>As vossas perguntas, respondidas.</h2></div><div><?php foreach($faq as $i=>$x): ?><details <?= $i===0?'open':'' ?>><summary><?= escP($x['pergunta']) ?></summary><p><?= nl2br(escP($x['resposta'])) ?></p></details><?php endforeach ?></div></section>
<section class="mk-final"><span class="mk-selo">O próximo capítulo começa aqui</span><h2>Mais tempo para viver o casamento.</h2><p>Juntem os convites, as pessoas e os preparativos num único lugar. Nós ajudamos a organizar o caminho até ao vosso dia.</p><a class="btn btn-ouro" href="registo.php">Começar agora <span aria-hidden="true">↗</span></a></section>
</main><footer>© <?= date('Y') ?> <?= escP(PLATAFORMA['nome']) ?> · <a href="login.php">Entrar</a></footer><script src="<?= asset('assets/icones.js') ?>"></script><script src="<?= asset('assets/ajuda.js') ?>"></script></body></html>
